version: '3.8'
services:
  circuitdubonheur:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - CDB
  test-db:
    image: postgres:13
    ports:
      - 5434:5434
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - CDB
networks:
  CDB:
    external: true
